### ISSUE TITLE
Fix date labels in trend plots

### ISSUE THREAD

**Issue by dharabor** [MAPF-Competition/web_resource#19]
Looks like the trend line (on our leaderboard) shows dates in USA month/day/year format. Suggest we update this to ISO 8601 format; i.e., yyyy-mm-dd

Also a comment/question. Is there a maximum number of labels that can appear? If so, what is this number and will the date labels be non-overlapping when it is reached?

**Comment by GreatenAnoymous** [comment]
The dates are now in ISO format( in the "develop" branch). Currently, there is no restriction on the number of date labels, which means that when there are many labels, they might overlap with each other. I can set a limit to prevent label overlap.

**Comment by GreatenAnoymous** [comment]
I've tested the visualization, and it turns out that the number of date labels displayed depends on the size of the window. The chart has the capability to automatically adjust the number of date labels shown on the screen, ensuring that the labels do not overlap with each other. Here's an example for reference: [ https://drive.google.com/file/d/1rRQzwIB25xi8wBJJaSaKSYFNF8dlWD30/view?usp=sharing]( https://drive.google.com/file/d/1rRQzwIB25xi8wBJJaSaKSYFNF8dlWD30/view?usp=sharing)
